import React from "react";
import type { Metadata } from 'next';
import { ContentLayout } from "../../components/ui/content-layout";

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'Privacy Policy for Onlyface.',
};

const PrivacyPolicy = () => {
  return (
    <ContentLayout title="Privacy Policy" subtitle="Last updated: October 02, 2023">
      <p>
        This Privacy Policy describes Our policies and procedures on
        the collection, use and disclosure of Your information when
        You use the Service and tells You about Your privacy rights
        and how the law protects You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service.
        By using the Service, You agree to the collection and use of
        information in accordance with this Privacy Policy.
      </p>

      <h2>Interpretation and Definitions</h2>
      <h3>Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have
        meanings defined under the following conditions. The following
        definitions shall have the same meaning regardless of whether
        they appear in singular or in plural.
      </p>
      <h3>Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul>
        <li>
          <strong>Account</strong> means a unique account created
          for You to access our Service or parts of our Service.
        </li>
        <li>
          <strong>Affiliate</strong> means an entity that controls,
          is controlled by or is under common control with a party.
        </li>
        <li>
          <strong>Application</strong> refers to Onlyface, the
          software program provided by the Company.
        </li>
        <li>
          <strong>Company</strong> refers to Onlyface.
        </li>
        <li>
          <strong>Country</strong> refers to: Taiwan
        </li>
        <li>
          <strong>Device</strong> means any device that can access
          the Service.
        </li>
        <li>
          <strong>Personal Data</strong> is any information that
          relates to an identified or identifiable individual.
        </li>
        <li>
          <strong>Service</strong> refers to the Application.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected
          automatically, either generated by the use of the Service
          or from the Service infrastructure itself.
        </li>
      </ul>

      <h2>Collecting and Using Your Personal Data</h2>
      <h3>Types of Data Collected</h3>
      <h4>Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with
        certain personally identifiable information that can be used
        to contact or identify You. Personally identifiable
        information may include:
      </p>
      <ul>
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Phone number</li>
        <li>Usage Data</li>
      </ul>

      <h3>Use of Your Personal Data</h3>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul>
        <li><strong>To provide and maintain our Service</strong></li>
        <li><strong>To manage Your Account</strong></li>
        <li><strong>For the performance of a contract</strong></li>
        <li><strong>To contact You</strong></li>
        <li><strong>To manage Your requests</strong></li>
      </ul>

      <h2>Security of Your Personal Data</h2>
      <p>
        The security of Your Personal Data is important to Us, but
        remember that no method of transmission over the Internet, or
        method of electronic storage is 100% secure.
      </p>

      <h2>Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, You can
        contact us:
      </p>
      <ul>
        <li>
          By email: support@onlyface.app
        </li>
      </ul>
    </ContentLayout>
  );
};

export default PrivacyPolicy;
